In [2]:
import numpy as np
y = np.array([44,21,37])
print(y)

# .shape informa formato da matriz
print(y.shape)
# ele tem nenhuma coluna, logo é um vetor

[44 21 37]
(3,)


In [3]:
x = np.array([[1.1, 1, 545, 1], [4.6, 0 ,345, 2], [7.2, 1, 754, 3]])
print(x)


[[  1.1   1.  545.    1. ]
 [  4.6   0.  345.    2. ]
 [  7.2   1.  754.    3. ]]


In [6]:
x = np.array([1.1, 1, 545, 1, 4.6, 0 ,345, 2, 7.2, 1, 754, 3]).reshape(3,4)
print(x)


[[  1.1   1.  545.    1. ]
 [  4.6   0.  345.    2. ]
 [  7.2   1.  754.    3. ]]


In [8]:
a = np.array([[1,1],[1,0]])
b = np.array([[1,0],[0,1]])
print(a-b)
print()
a = np.array([[0,1],[1,-1]])
print(a*-2)

[[ 0  1]
 [ 1 -1]]

[[ 0 -2]
 [-2  2]]


In [9]:
x = np.array([[4,5],[2,4],[3,3]])
b = np.array([3,-2])
print(np.dot(x,b))
c = np.array([[3,-2],[-2,5]])
print(np.dot(x,c))


[ 2 -2  3]
[[ 2 17]
 [-2 16]
 [ 3  9]]
